podTemplate(name: 'maven-template', label: 'maven', cloud: 
'kubernetes', namespace: 'default', containers: [
  containerTemplate(
    name: 'maven', 
    image: 'maven:3-alpine', 
    ttyEnabled: true, 
    alwaysPullImage: true,
    workingDir: '/home/jenkins'
  )
  ]){

  node('maven') {
    stage('Clone git') {
      git 'https://github.com/sindar225/simple-java-maven-app.git'
    }    
	
	stage('Build a Maven project') {
      git 'https://github.com/sindar225/simple-java-maven-app.git'
      container('maven') {
          sh 'mvn -B clean package'
      }
    }
  }
}